### ISSUE TITLE
TypeError: Cannot read property 'sort' of undefined

### ISSUE THREAD

**Issue by budparr** [chrisdmacrae/serverless-atomic-algolia#1]
Hey, Chris. I'm getting the following error. Appears to be an issue with my index, but I am declaring an `objectID`:
```
new webtask request 1526045152062.324070
{
  "code": 400,
  "error": "Script returned an error.",
  "details": "TypeError: Cannot read property 'sort' of undefined",
  "name": "TypeError",
  "message": "Cannot read property 'sort' of undefined",
  "stack": "TypeError: Cannot read property 'sort' of undefined\n    at idsFromIndex (/data/_verquire/atomic-algolia/0.3.15/node_modules/atomic-algolia/lib/utils/idsFromIndex.js:15:9)\n    at calculateOperations (/data/_verquire/atomic-algolia/0.3.15/node_modules/atomic-algolia/lib/utils/calculateOperations.js:23:23)\n    at /data/_verquire/atomic-algolia/0.3.15/node_modules/atomic-algolia/lib/update.js:34:30\n    at <anonymous>"
}
finished webtask request 1526045152062.324070 with HTTP 400 in 1791ms
```

**Comment by budparr** [comment]
I'm going to close this for now, as I think I know what the error is.
